#!/bin/bash

readonly IMAGE="wlruys/nuwest"


# ----------
# Functions.

function s_has_cuda() {
        hash nvcc
}

function s_tag() {
        if s_has_cuda; then
                echo "ampere"
        else
                echo "cpu"
        fi
}

function s_assume() {
        hash docker >/dev/null 2>&1 || \
                { echo "missing docker"; return 1; }
}

function s_set_up() {
        # Set up the environment.

        if ! docker images | grep "${IMAGE}" | grep "$(s_tag)" > /dev/null; then
                docker pull "${IMAGE}:$(s_tag)" || \
                        { echo "could not pull the docker image"; return 1; }
        fi
}

function s_exe() {
        # Run an example on the given path.
        local path="${1}"

        [ -z "${path}" ] && \
                { echo "help: ${0} scripts/mini_boltzmann_cpu.py -N 100000 -s 10"; return 1; }

        if s_has_cuda; then
                #docker run -it --runtime=nvidia --gpus all -e "DISPLAY=$DISPLAY" wlruys/nuwest:cpu bash
                docker run \
                       --runtime=nvidia \
                       --gpus all \
                       --volume $(pwd):/app \
                       --workdir /app \
                       "${IMAGE}:$(s_tag)" \
                       python \
                       "$@" || \
                        { echo "could not run"; return 1; }
        else
                docker run \
                       -e OPENMP_NUM_THREADS=1 \
                       --volume $(pwd):/app \
                       --workdir /app \
                       --user demo:$(id -g) \
                       "${IMAGE}:$(s_tag)" \
                       python \
                       "$@" || \
                        { echo "could not run"; return 1; }
        fi

        #find -type d -name "__pycache__" | xargs rm -rf
        #rm -r pk_cpp
}

function main() {
        s_set_up || return 1
        s_exe "$@" || return 1
}

main "$@"
